### ISSUE TITLE
BCUL importer

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-text-acquisition#118]
Some background in [Call-BCUL](https://docs.google.com/document/d/1R_9cSZ6WAV39eCqDjw1vu2edBXaGD4-27BXhKNDl50U/edit).
1. [x] First version based on sample
2. Second version based on pilot data

**Comment by piconti** [comment]
Second version based on pilot data (with JSON mit files) has been done. 
The Scriptorium API was not forking properly due to certificate issues, so further modifications might be necessary for this specific case. 
Otherwise, the code is ready to be merged.

**Comment by piconti** [comment]
Scriptorium API is fixed, now necessary to ingest the remainder of the data in staging and merge the code.

- [ ] Ingest into canonical format rest of tiltes from first batch
- [ ] Finalize code comments and documentation
- [ ] Merge into master

**Comment by piconti** [comment]
Current code is done and is ready to be merged as soon as it's commented, and documented. 

this will be done following the merge of the bugfix_ci_metadata branch which is in the process of being commented and prepared for merging.
