### ISSUE TITLE
Documentation of  the meaning of the coordinates

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-text-acquisition#19]
@mromanello Could we specify the exact meaning of the coordinates in the schema documentation?
I need to add the line coordinates for NZZ (we need to reconstruct that as TETML is not able to produce word and line boxes at the same time) and I am a bit unsure what the numbers actually mean.  llx, lly, urx, ury 

An in more detail:
Meaning, in your case (see below for an example from GDL) the urx,ury of the last word in the line always specify the extension of the line? (Meaning, if a line consists of a centered word within a column, the line would just be the bounding box of the word?

```
  "r": [
      {
         "c": [
            66,
            162,
            458,
            923
         ],
         "p": [
            {
               "l": [
                  {
                     "c": [
                        108,
                        183,
                        449,
                        230
                     ],
                     "t": [
                        {
                           "c": [
                              108,
                              183,
                              255,
                              230
                           ],
                           "tx": "BANQUE",
                           "s": 21
                        },
                        {
                           "c": [
                              262,
                              183,
                              449,
                              230
                           ],
                           "tx": "FEDERALE",
                           "s": 21
                        }
                     ]
                  }
               ]
            },
```

**Comment by mromanello** [comment]
this has been now spelled out in the json schemas see [issue 14](https://github.com/impresso/impresso-schemas/issues/14), so closing this issue
