### ISSUE TITLE
bug: missing pages on search with daterange filter

### ISSUE THREAD

**Issue by tvanbeek** [impresso/impresso-text-acquisition#27]
When querying the data without any filters, the whole corpus returns, currently `4.453.400` articles. However, when I filter with just a daterange limit but with min/max time values that should include the whole timespan of the dataset, fewer results are returned.

Example daterange filter `from 1200-01-01 until 2020-01-01`, results `4.157.585`. So we have `295.815` with wrong/missing dates or some other problem causing this behaviour.

**Comment by mromanello** [comment]
old backlog that was already fixed, thus closing it
