### ISSUE TITLE
importer for SWA newspaper data

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#52]

**Comment by mromanello** [comment]
things that remain to be done:
- [ ] test UBB's IIIF endpoint once their tif -> jp2 conversion is done (ETA 20.10.2019)
- [ ] read access rights from JSON file; Elias has added access rights information to the spreadsheet that accompanies their export

**Comment by ehoelzl** [comment]
This has been fixed and all data is now on `original-canonical-testing`
