### ISSUE TITLE
importer for BNF newspaper data

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#56]
(a first version has been already implemented (see branch `BNF-acquisition`) )

TODO:
- [ ] test importer with another newspaper that @e-maud is currently acquiring from BNF; the Mets/Alto format is slightly different, thus small adaptations/changes may be required
- [ ] investigate how to ingest metadata from BNF library catalogue (and open corresponding issue in `impresso-master-db` repository)

**Comment by e-maud** [comment]
Complementing information:

1. **[BNF batch 1]** The existing "BNF" importer was developed for titles available here: http://api.bnf.fr/documents-de-presse-numerises-en-mode-article
- [ ] run the BNF importer on all titles available at this URL and check if everything is all right (esp. IIIF links)
- [ ] investigate the metadata for those titles (format, content) from what is online
- [ ] @e-maud: produce access right file

2. **[BNF batch 2]** Another bunch of data will arrive on the NAS, _in the same format_:
- [ ] run the BNF importer on those titles and check if everything is all right (esp. IIIF links)
- [ ] get the metadata for those titles (will send info via email)
- [ ] @e-maud: produce access right file

3. **[BNF-EN batch 1]** Another bunch of data from Europeana Newspapers, in a _slightly different format_, is available here: http://api.bnf.fr/documents-de-presse-numerises-en-mode-article-du-projet-europeana-newspapers
- [ ] derive a "BNF-EN" importer from the "BNF" importer. For info, there is a text version (JSON) of those sources available [here](http://api.bnf.fr/texte-des-documents-de-presse-du-projet-europeana-newspapers-xixe-xxe-siecles) but it is not sure there is still the coordinate information.
- [ ] test ingestion of all titles
- [ ] investigate the metadata for those titles (format, content) from what is online
- [ ] @e-maud: produce access right file

**Comment by piconti** [comment]
@e-maud I believe that this issue can be closed, since the importer was created and the data has been part of this last ingestion.

**Comment by e-maud** [comment]
You're completely right, thanks a lot for all the efforts and work on this BnF data.
