### ISSUE TITLE
importer for BL data

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#60]
- write an importer for British Library data
    - data sample at `text_importer/data/sample_data/BL/`
- importer will be a custom version of mets/alto importer
- ongoing development in branch `BL-acquisition`

**Comment by mromanello** [comment]
Update (after email exchange with Yann and Rossitza):
- use NLP numbers as newspaper canonical IDs
- time horizon for IIIF links still uncertain
- license (access rights) needs to be confirmed internally; but `closed` for the time being

**Comment by mromanello** [comment]
what remains to do:

- [ ] Test on more recent issues to see if content items/images are correct
- [ ] test on more materials once they become available

**Comment by ehoelzl** [comment]
There are currently 19 issues for the British Library, however None of them have images in them (only `ad` and `article`) types. I left a TODO in `bl/classes.py`
