### ISSUE TITLE
FedGaz: physical pages may not match logical page number

### ISSUE THREAD

**Issue by aflueckiger** [impresso/impresso-text-acquisition#70]
In FedGaz, we have some special cases where the physical page number (pages in PDF) doesn't match the logical page numbering (i.e., printed page numbers) as there are some supplements included in the article. The supplements don't count towards the logical page numbering in the original data.

As we take the logical page numbering of the Bundesarchiv as a given, our heuristic to find the logical article boundary fails. In such case, their last page gets pruned. Although it is possible to program a workaround, it is not worth it for the time being. 

For example: https://www.amtsdruckschriften.bar.admin.ch/viewOrigDoc.do?id=10014366 (page 110)

**Comment by mromanello** [comment]
should I reopen this, @aflueckiger ?

**Comment by simon-clematide** [comment]
This is not related. It's just that the logical page numbers and our numbered physical pages images do not match in general.
