### ISSUE TITLE
missing coordinates JSON property in issues of METS/ALTO importer

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-text-acquisition#72]
In the `issues` files of the canonical data produced with the RERO METS/ALTO importer, the `c` (coordinates) property is missing in the `m` object.

This bug was noticed during image import for image similarity computation. Since the IIIF link is not in the `issues` file (as it is the case for BNL data), one needs to rebuild it and therefore need the coordinates.

For example, in the `DTT-1940-issues.jsonl.bz2`, the following items does not have the `c`:
```
"m": {
        "id": "DTT-1940-01-02-a-i0044",
        "tp": "image",
        "pp": [
          6
        ],
        "t": "UNKNOWN"
      },
```

**Comment by mromanello** [comment]
to be checked whether the coords are there in the source file;
