### ISSUE TITLE
Unknown coordinates for SWA tokens

### ISSUE THREAD

**Issue by ehoelzl** [impresso/impresso-text-acquisition#77]
Some issues from SWA have missing coordinates for tokens. This only happens for "handelsztg" newspaper for issues before 1900 (e.q. handelsztg-1862-05-24), and for around 190 issues.

Here is an example of missing coordinates for a token:
```
<String STYLE="superscript" WC="1." CONTENT="6" ID="String_68211" />
```

from file `BAU_1_000094150_1862_0258.xml` inside archive `schweiunh_000094150_DSV01_1862.zip`.

For this issue, only two tokens have missing coordinates. I'm still not sure how many tokens overall do not have coordinates, but the number seems quite low (only happens occasionally for a fews issues).

**Comment by eliaskreyenbuehl** [comment]
I looked into the production logs and everything went normally with schweiunh_000094150_DSV01_1862 For the moment I have no explanation for the missing coordinates. Since it occurs not so often, I suggest to ignore it.

**Comment by ehoelzl** [comment]
> I looked into the production logs and everything went normally with schweiunh_000094150_DSV01_1862 For the moment I have no explanation for the missing coordinates. Since it occurs not so often, I suggest to ignore it.

The problematic issues do not only appear in that zip files. In fact the same issue appears in multiple zip files.

Another problem with 5 issues: some page files are missing. 
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_0439.xml
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_ProfilS.xml
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_0218.xml
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_0963.xml
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_0072.xml
- schwha_000094152_DSV01_1884/ocr/schwha_000094152_DSV01_1884_alto/BAU_1_000094152_1884_1191.xml

Could you look into this ?

**Comment by simon-clematide** [comment]
@ehoelzl Would it be possible to just use the line coordinates (and log it for having some statistics at the end)?

**Comment by ehoelzl** [comment]
> @ehoelzl Would it be possible to just use the line coordinates (and log it for having some statistics at the end)?

Do you mean use the coordinates of the parent block ? For now, the tokens are not added into the `page_data`, but since most of the missing ones are within lines, then the line coordinate will take the missing token into account (in the image). Also, a note is added to the page data via the `n` attribute, indicating missing coordinates and the XML id of the concerned object.

**Comment by ubunibas** [comment]
@ehoelzl: I forwarded the empty ALTO file issue to our OCR service provider. There seem to be some inconsistencies regarding OCR creation for this issue. Do you know how many pages are affected totally?

Regarding the missing coordinates: it still seems to be valid ALTO-XML and in my opinion it would be difficult to solve, like this issue is produced by Abbyy Alto output. If its only a few cases I would not further pursue it. My experience with Abbyy support, is not really great ...

**Comment by ubunibas** [comment]
@ehoelzl : I ran some tests. The six files seem to be the only one, where the Alto-XML is empty and the txt-file contains content. We'll rerun the OCR but I believe for the moment we might ignore this issue?

**Comment by ehoelzl** [comment]
Issue has been fixed. All tokens with missing coordinates are discarded and added to the page note (`n` attribute in page data)

Missing pages re-computed and sent back to us so we can re-ingest the specific issues with missing pages.
