### ISSUE TITLE
import for BCUL newspapers

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#80]
Preliminary tasks:
- [x] test connection with their MySQL DB (read-only mode)
- [x] @e-maud to give @ehoelzl the list of titles to be ingested (best to attach it to this issue)
- [x] match list of titles to be ingested with IDs of objects/records in the DB
- [x] get the path to the NAS where the XML files to be ingested are found
- [x] Produce table with columns `[iss_id, journal, api_link, fs_path]`

Some useful info:
- API call to get the Metadata of an issue is: https://scriptorium.bcu-lausanne.ch/api/item/[iss_id]/meta
- If `fs_path` is empty, then relative path is used with `iss_date_added` in format `YYYY/MM/DD`

Pending:
- [x] test IIIF endpoint
- [x] get access to their NAS to access raw XML data

**Comment by ehoelzl** [comment]
What has been done on this issue:
- Page and issue parsing should be ok (on current sample). Both classes `BCULNewspaperIssue` and `BCULNewspaperpage`
- `detect_issues` works with files on a certain file system. It looks for the "mit" file for each issue and parses from it.
