### ISSUE TITLE
add font styles for BNL importer

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#81]
- unlike Olive/Rero, they are expressed at the level of page
   - this requires us to add a style (`s`) field in the canonical page schema;
   - doing otherwise will increase *a lot* processing times, as the importer needs to jump to issue level to pages and back
- conflate information about font-family ("Times New Roman") and font-type ("bold italic") into the same `s` -> `f` field: we will have e.g. "times_new_roman-bold-italic"

**Comment by ehoelzl** [comment]
This has been treated in #62 . Importer has run and all the new data is in `original-canonical-testing`. Waiting for sanity check before merging.

**Comment by ehoelzl** [comment]
Can this issue be closed ? @mromanello
