### ISSUE TITLE
merging TETML/FedGaz importers

### ISSUE THREAD

**Issue by aflueckiger** [impresso/impresso-text-acquisition#93]
Hi @mromanello 

I disentangled the FedGaz importer and the generic TETML importer. Neither code nor docstrings are a beauty. Compared to the other formats, TETML is less structured in terms of proper separation of metadata and content. Additionally, there is an ugly heuristic search for FedGaz to find the correct article segmentation. Nevertheless, I think it reached a level that is ready to merge. See here: https://github.com/aflueckiger/impresso-text-acquisition/tree/disentangle-tetml-fedgaz

Just a few remaining questions:

- How to include xml elements or ASCII drawing in a docstring (verbatim)? For example, 
    ``
    <Image id="I0" extractedAs=".tif" width="1404" height="2367" colorspace="CS0" bitsPerComponent="1"/>
    ``
    I tried double quotes and `.. code-block:: HTML` without success.

- There are some redundant attributes because of inheritance (e.g. text_importer.importers.tetml.classes.TetmlNewspaperPage).
What is the right way to deal with this? Other importers have the same issue.

- I used a script `show_canonical_boxes.py` to check the segmentation into articles (performed heuristically for FedGaz) regions, paragraphs, tokens etc. Where should I put it? Currently, it is located in the FedGaz importer. Perhaps, it is of greater use and we could highlight it more prominently.

Is there anything else missing? If you notice oddities in the code, I am happy for some feedback (always keen to learn from you).

**Comment by mromanello** [comment]
All good, it’s already merged :)
